package com.example.demo;

import io.micrometer.core.instrument.util.StringUtils;
import lombok.extern.slf4j.Slf4j;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.Banner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.core.env.Environment;

import java.net.InetAddress;
import java.net.UnknownHostException;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
//@EnableSwagger2
@MapperScan("com.example.demo.mapper")
@Slf4j
public class DemoApplication {
    public static void main(String[] args) {
//        SpringApplication.run(DemoApplication.class, args);
        SpringApplication app = new SpringApplication(DemoApplication.class);
        Environment env = app.run(args).getEnvironment();
        app.setBannerMode(Banner.Mode.CONSOLE);
        logApplicationStartup(env);

    }

    private static void logApplicationStartup(Environment env) {
        String protocol = "http";
        if (env.getProperty("server.ssl.key-store") != null) {
            protocol = "https";
        }
        String serverPort = env.getProperty("server.port");
        String contextPath = env.getProperty("server.servlet.context-path");
        String hostAddress = "localhost";
        String swaggerPath = "";
        if (StringUtils.isBlank(contextPath)) {
            swaggerPath = "/swagger-ui";
        } else {
            swaggerPath = contextPath + "/swagger-ui";
        }
        try {
            hostAddress = InetAddress.getLocalHost().getHostAddress();
        } catch (UnknownHostException e) {
            log.warn("The host name could not be determined, using `localhost` as fallback");
        }
        if (log.isInfoEnabled()) {
            log.info(("----------------------------------------------------------\n" +
                            "\t应用程序“{}”正在运行中......\n" +
                            "\t配置文件: {}\n" +
                            "\t\tswagger接口文档访问 URL:\n" +
                            "\t\t\t本地: {}://localhost:{}{}\n" +
                            "\t\t\t外部: {}://{}:{}{}\n" +
                            "----------------------------------------------------------"),
                    env.getProperty("spring.application.name"),
                    env.getActiveProfiles(),
                    protocol,
                    serverPort,
                    swaggerPath,
                    protocol,
                    hostAddress,
                    serverPort,
                    swaggerPath);
        }
    }

}


